if(EXISTS "/home/laura/Documents/GitHub/RoboCup-Equipo2/tests/runTests[1]_tests.cmake")
  include("/home/laura/Documents/GitHub/RoboCup-Equipo2/tests/runTests[1]_tests.cmake")
else()
  add_test(runTests_NOT_BUILT runTests_NOT_BUILT)
endif()
